#!/bin/bash
#
#  %FFILE%
# 
#  This file is a single pbs job for submission qith qsub
#
#  Created by:    Michael Dacre
#  Date Created:  %FDATE%
#  Last modified: 
#
#PBS -S /bin/bash
#PBS -m ae
#PBS -l nodes=1:ppn=1 -l pmem=2gb -l mem=2gb
cd $PBS_O_WORKDIR
export PYTHON3PATH="/home/dacre/lib/python:/home/dacre/lib/python:/home/dacre/lib/python"
export PYTHONPATH="/home/dacre/lib/python:/home/dacre/lib/python:/home/dacre/lib/python"

%HERE%
